added sortByWeight task
bootcamp-places/online-editor-tasks pull request #1
Opened 2022-05-23 13:16 UTC by koshacool

2022-05-23 13:58 UTC, dosandk commented on tracks/arrays/01-sortByWeight/readme.md
> +Потрібно реалізувати функцію `sortByWeight`, яка приймає массив чисел та сортує по сумі кожного елементу
було би непогано навести приклад яка логіка підрахунку ваги елементу:
```
const arr = [3, 1, '55', 33, '20];
```

| element | weight |
|:---:        |:---:       |
| 3            | 3           |
| 1             | 1                |
| 55          | 5 + 5 = 10 |
| 33          | 3 + 3 = 6  |
| 20          | 2 + 0 = 2. |

2022-05-23 14:00 UTC, dosandk commented on tracks/arrays/01-sortByWeight/solution/index.js
> +    if (sum1 < sum2) {
а чому би не скоротити обрахунки?
```
return sumNumbers(a) - sumNumbers(b);
```

2022-05-23 14:01 UTC, dosandk commented on tracks/arrays/01-sortByWeight/solution/index.js
> +      .toString()
для чого тут метод `toString`?

2022-05-23 14:02 UTC, dosandk commented on tracks/arrays/01-sortByWeight/readme.md
> +  Потрібно реалізувати власний метод сорт в якому будуть сумуватись значення
тут було би непогано дати посилання на довідник mdn де є опис методу `sort`

2022-05-23 14:03 UTC, dosandk commented on tracks/arrays/01-sortByWeight/readme.md
> +Потрібно реалізувати функцію `sortByWeight`, яка приймає массив чисел та сортує по сумі кожного елементу
було би непогано додати якийсь практичний кейс використання цієї функції

2022-05-23 14:03 UTC, dosandk commented on tracks/arrays/01-sortByWeight/readme.md
> +  '20',
чому `20` іде після 3?

2022-05-23 14:04 UTC, dosandk commented on tracks/arrays/01-sortByWeight/readme.md
> +  Потрібно реалізувати власний метод сорт в якому будуть сумуватись значення
ну і ще якійсь підказки, наприклад як перевести стрічку до числа, або якийсь опис роботи методу `sort` - простими словами

2022-05-23 14:05 UTC, dosandk commented on tracks/arrays/01-sortByWeight/solution/readme.md
> +Розв'язання цієї задачі може виглядати ось так:
було би добре дати пояснення, покроково, чому реалізація має виглядати саме так.
Ось приклад: https://github.com/dosandk/online-editor-tasks/tree/master/tracks/basic/13-removeByIndex/solution

2022-05-23 14:06 UTC, dosandk requested changes
@koshacool глянь будь ласка коменти

2022-05-23 14:08 UTC, koshacool commented on tracks/arrays/01-sortByWeight/solution/index.js
> +      .toString()
Тому що numbers не мають split method. ТАк як дані в масиві можуть бути як числа(123)  так і стрінги ('123')

2022-05-23 14:49 UTC, RomanKushytskyy commented on tracks/arrays/01-sortByWeight/readme.md
> +Потрібно реалізувати функцію `sortByWeight`, яка приймає массив чисел та сортує по сумі кожного елементу
@dosandk шось не можу придумати жодного толкового кейсу нажаль ((. Надалі буду краще продумувати завдання, щоб було побільше практичних кейсів

2022-05-23 22:25 UTC, dosandk commented on tracks/arrays/01-sortByWeight/readme.md
> +  Потрібно реалізувати власний метод [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort?retiredLocale=uk) в якому будуть порівнюватись елементи масиву.
`У власній реалізації методі` -> `У власній реалізації методу`

2022-05-23 22:27 UTC, dosandk commented on tracks/arrays/01-sortByWeight/solution/readme.md
> +Так як функція приймає массив як із числами так і стрічки з числами, потрібно спочатку привести значення до стрічки(так як числа не мають методу (split))
'до стрічки(' -> 'до стрічки (' 
після 'стрічки' до круглої дужки ставиться пробіл

2022-05-23 22:29 UTC, dosandk commented on tracks/arrays/01-sortByWeight/solution/readme.md
> +після цього розбити стрічку на елементи методом split і вже після цього просумувати всі елементи(при додаванні потрібно не забути перевести стрічку в число методами parseInt або parseFloat)
перше що запитає людина яка буде дивитись на цю реалізацію: а в якому випадку використати `parseFloat`? Чому цього немає в рішенні?

2022-05-23 22:32 UTC, dosandk commented on tracks/arrays/01-sortByWeight/solution/readme.md
>    const sumNumbers = number =>
чому запитав про `toString`, бо аргумент функції має назву "number", але насправді це не завжди число, вірно?
А другий момент, метод  "sumNumbers" не просто сумує числа, він вираховує вагу елементу масиву, тому може краще назвати його `getWeight`?

```
const getWeight = element => ...
```

2022-05-24 06:14 UTC, koshacool commented on tracks/arrays/01-sortByWeight/solution/readme.md
> +після цього розбити стрічку на елементи методом split і вже після цього просумувати всі елементи(при додаванні потрібно не забути перевести стрічку в число методами parseInt або parseFloat)
Видалив згадку про parseFloat так як в  цьому немає потреби, ми ніколи не будемо мати десятичних чисел через .split('')

2022-05-24 07:04 UTC, dosandk commented on tracks/arrays/01-sortByWeight/solution/index.js
> +      .toString()
good 👍

2022-05-24 08:15 UTC, koshacool commented
@dosandk порезолвай пліз виправлені ремарки, а то не понятно чи все пофіксав чи ні )

2022-05-24 20:56 UTC, dosandk commented on tracks/arrays/01-sortByWeight/readme.md
> +Потрібно реалізувати функцію `sortByWeight`, яка приймає массив чисел та сортує по сумі кожного елементу
👍

2022-05-24 20:57 UTC, dosandk approved these changes
good 👍

2022-05-24 20:57 UTC, merged