create createDateFromArray task
bootcamp-places/online-editor-tasks pull request #12
Opened 2022-07-20 09:21 UTC by trotsm

2022-07-26 11:05 UTC, dosandk commented on tracks/arrays/03-createDateFromArray/readme.md
> +    {id:1, date: 9, time: null},
а для чого в цьому методі `id` та `time` значення?
чому цей масив не може виглядати ось так:
```
const dateArray = [
  { foo: 9.       },
  { foo: 7        },
  { foo: 2022 },
];

createDateFromArray(dateArray, 'foo', '/');
```

ну а тест має тестувати використання аргументів `property`, `divider`

2022-07-26 11:06 UTC, dosandk commented on tracks/arrays/03-createDateFromArray/index.spec.js
> +  it('should return data in correct format', () => {
а де корнер-кейс?
наприклад в об'єкті. не має поля `date`?
або ми передали порожній масив?
або кількість елементів в масиві більше або меньше 3х?

2022-07-26 11:06 UTC, dosandk commented on tracks/arrays/03-createDateFromArray/readme.md
> +Необхідно реалізувати функцію `createDateFromArray`, яка приймає в якості аргументу
було би добре навести приклад, коли таке може статись

2022-07-26 11:07 UTC, dosandk requested changes
@trotsm будь ласка, глянь на коментарі

2022-07-31 08:16 UTC, trotsm commented on tracks/arrays/03-createDateFromArray/readme.md
> +    {id:1, date: 9, time: null},
Значення `id `та `time `для того, щоб емітувати реальні дані. В реальному житті вкрай рідко бувають такі дані, як 
```
const dateArray = [
  { foo: 9.       },
  { foo: 7        },
  { foo: 2022 },
];
```
Як правило, приходить великий набір різних даних, з яких треба обрати необхідні.
В тесті приймаються: масив даних, property, divider.

2022-07-31 09:32 UTC, closed without merging