added uniqueValues task
bootcamp-places/online-editor-tasks pull request #2
Opened 2022-05-23 15:43 UTC by koshacool

2022-05-23 22:14 UTC, dosandk commented on tracks/arrays/02-uniqueValues/readme.md
> +Нам ж потрібно отримати список користувачів, які грали у нашу гру цього тижня, не важливо скільки разів.
`Haм же`

2022-05-23 22:15 UTC, dosandk commented on tracks/arrays/02-uniqueValues/readme.md
> +Алгоритм дій має бути наступним:
було би добре ще підказати як перетворити колекцію `Set` назад до масиву

2022-05-23 22:16 UTC, dosandk commented on tracks/arrays/02-uniqueValues/solution/readme.md
> +Можуть бути різні варіанти імплементації цієї функції, але найшвидший це використати колекцію [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)
Чому "найшвидший"? тому що працює швидше за інші з точки зору перформенсу?
Чи "найшвидший", бо потребує меньше зусиль при написанні коду?

2022-05-23 22:17 UTC, dosandk commented on tracks/arrays/02-uniqueValues/solution/readme.md
> +Тобто ми перетворюємо масив у [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) колекцію (в якій значення будуть присутні лише 1 раз), яку зразу ж перетворює
достатньо один раз дати посилання на `Set` і далі вже не повторювати

2022-05-23 22:19 UTC, dosandk commented on tracks/arrays/02-uniqueValues/solution/readme.md
> +Тобто ми перетворюємо масив у [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) колекцію (в якій значення будуть присутні лише 1 раз), яку зразу ж перетворює
spread оператору не існує в природі, існує тільки `spread syntax`.
`...` ці три крапки схожі на оператор, але таким не є https://esprima.org/demo/parse.html?code=const%20arr%20%3D%20%5B'a'%2C%20'b'%2C%20'c'%5D%3B%0Aconst%20copy%20%3D%20%5B...arr%5D%3B

`...` - це Spread Element якщо бути абсолютно точним

2022-05-23 22:21 UTC, dosandk commented on tracks/arrays/02-uniqueValues/solution/readme.md
> +Можуть бути різні варіанти імплементації цієї функції, але найшвидший це використати колекцію [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)
Тут було би добре пояснити людям, чого саме `Set` нам підійде краще за інші рішення.
Плюс одразу зазначити як себе поведе `Set` якщо в масиві будуть міститись не примітивні значення, а об'єкти

2022-05-23 22:21 UTC, dosandk commented on tracks/arrays/02-uniqueValues/solution/index.js
> +export const uniqueValues = (array = []) => [...new Set(array)]
крапка з комою `;` в кінці

2022-05-23 22:21 UTC, dosandk commented on tracks/arrays/02-uniqueValues/solution/readme.md
> + const uniqueValues = (array = []) => [...new Set(array)]
крапка з комою `;` в кінці

2022-05-23 22:23 UTC, dosandk commented on tracks/arrays/02-uniqueValues/readme.md
> +* перетворити масив у колекцію Set
В markdown, усі конструкції з JavaScript слід загортати у зворотні лапки `Set` - це дає підсвітку коду та спрощую читання опису

2022-05-23 22:24 UTC, dosandk requested changes
@koshacool глянь будь ласка коменти

2022-05-24 05:51 UTC, koshacool commented on tracks/arrays/02-uniqueValues/solution/readme.md
> +Можуть бути різні варіанти імплементації цієї функції, але найшвидший це використати колекцію [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)
Можливо не варто так детально все розписувати, а стимулювати людей читати документацію?

2022-05-24 06:00 UTC, koshacool commented on tracks/arrays/02-uniqueValues/solution/index.js
> +export const uniqueValues = (array = []) => [...new Set(array)]
думаю варто поправити лінтер шоб таке не ревювати )

2022-05-24 20:53 UTC, dosandk approved these changes
good 👍

2022-05-24 20:54 UTC, dosandk commented on tracks/arrays/02-uniqueValues/solution/readme.md
> +Можуть бути різні варіанти імплементації цієї функції, але найшвидший це використати колекцію [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)
детально розипсувати не треба, але якщо ми даємо рішення для задачі, то маємо обгрунтувати чому саме таке рішення ми вважаємо оптимальним для задачі

2022-05-24 20:55 UTC, dosandk commented on tracks/arrays/02-uniqueValues/solution/index.js
> +export const uniqueValues = (array = []) => [...new Set(array)]
@koshacool лінтер додав, треба взяти pull з форку

2022-05-24 20:55 UTC, merged