add objects/removeProperties exercise
bootcamp-places/online-editor-tasks pull request #3
Opened 2022-05-23 18:55 UTC by YevheniiKolomiiets

2022-05-23 21:57 UTC, dosandk commented on tracks/objects/16-removeProperties/index.spec.js
> +  it('should return empty empty object if it was passed to function like an argument', () => {
треба попрвити опис: `should return empty empty`, зайве `empty`

2022-05-23 22:09 UTC, dosandk commented on tracks/objects/16-removeProperties/solution/index.js
> +    delete obj[key]
використання `delete` - це не дуже добра ідея на практиці.
@YevheniiKolomiiets будь ласка глянь на вже існуючу задачу: https://github.com/dosandk/online-editor-tasks/tree/master/tracks/basic/09-omit

`delete` може призвести на практиці до неочікуваних результатів, бо змутує, зміне оригінальний об'єкт, що зазвичай як раз і не потрібно. І всі інші частини коду вже матимуть справу зі змутованим об'єктом, бо об'єкт передається по посиланню.

Тому один із варіантів, який може захистити від цього, - це скопіювати об'єкт, але цвісно це не врятує від ситуації коли ми видаляємо вкладені властивості, які теж можуть бути об'єктами.

Тому від `delete` краще взагалі відмовитись

2022-05-23 22:11 UTC, dosandk commented on tracks/objects/16-removeProperties/readme.md
> +removeProperties({ one: 'one', two: 'two', three: 'three' }, ['one', 'two']); // { three: 'three' } - видаляємо 'one' i 'two'
було би добре що би в прикладі була данні пов'язані з чимось придметним:
це можуть бути товари, фрукти, користувачі, все що завгодно крім `one`, 'two`, `three`.
Це дуже спрощую у новачків розуміння задачі

2022-05-23 22:12 UTC, dosandk requested changes
@YevheniiKolomiiets будь ласка, глянь на коменти

2022-05-24 07:12 UTC, YevheniiKolomiiets commented on tracks/objects/16-removeProperties/solution/index.js
> +    delete obj[key]
@dosandk не помітив задачу про omit. Написав інше рішення. Ці задачі дуже подібні, можна закривати цей МР. На твій розсуд.

2022-05-24 20:53 UTC, dosandk approved these changes
good 👍

2022-05-24 20:57 UTC, merged