add basic/removeStringSpace
bootcamp-places/online-editor-tasks pull request #6
Opened 2022-05-28 09:26 UTC by YevheniiKolomiiets

2022-05-28 10:30 UTC, dosandk commented on tracks/basic/14-removeStringSpace/readme.md
> +  Зверніть увагу на метод [slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice)
тут, мабуть треба звернути увагу на метод `replace`

2022-05-28 10:31 UTC, dosandk commented on tracks/basic/14-removeStringSpace/solution/readme.md
> +* Для зміни символів можна використати метод [`replace`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace)
тут було би добре додати короткий опис того що таке `/\s/g', а семе познайомити користувача з регулярними виразами, дати трохи контексту, а за додатковою інфою вже відправити за посиланням

2022-05-28 10:32 UTC, dosandk commented on tracks/basic/14-removeStringSpace/solution/readme.md
> +
також можно згадати метод `trim` - який дозволяє видалити пробільні символи на початку і на прикінці стрічки, але в нього є обмеження - він не працює з пробільними символами в середині стрічки, тому для вирішення данної задачі підійде метод `replace`

2022-05-28 10:33 UTC, dosandk requested changes
@YevheniiKolomiiets глянь будь ласка до коментів

2022-06-04 06:31 UTC, YevheniiKolomiiets commented
@dosandk апдейтнув

2022-06-06 20:07 UTC, dosandk approved these changes
good 👍

2022-06-06 20:07 UTC, merged